#!/bin/zsh

# Description: Replaces spaces with hyphens for the data in the clipboard

# Get the clipboard content
content=$(pbpaste)

# Make replacements
#content=$(echo "$content" | sed -E 's/[-/\\:;&\*]/ /g')
#content=$(echo "$content" | sed -E 's/["“”%‘’\?]//g' | sed -E "s/[']//g")
content=$(echo "$content" | sed -E 's/-/ /g')
content=$(echo "$content" | sed -E 's/ +/ /g')
content=$(echo "$content" | sed -E 's/ /-/g')

# Copy the modified content back to the clipboard
echo -n "$content" | pbcopy
echo "$content"